[build]
  command = "npm run build"
  # Next.js 插件会自动处理 publish 目录和 API Routes

[functions]
  node_bundler = "esbuild"
  directory = "netlify/functions"
  # 设置函数超时时间
  timeout = 30
  
[functions.ai-grade]
  # 外部依赖包括
  external_node_modules = ["node-fetch", "@supabase/supabase-js"]

# Next.js 插件配置 - 确保支持 App Router API Routes
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Headers 配置
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

# 构建环境变量
[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"