# 简化配置，只使用环境变量禁用插件
[build]
  command = "npm run build"
  publish = "out"
  
[build.environment]
  NODE_VERSION = "18"
  # 尝试禁用Next.js插件的环境变量
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  DISABLE_NETLIFY_NEXT = "true"

[functions]
  directory = "netlify/functions"